[env]
TERM = "xterm-256color"

[selection]
save_to_clipboard = true

[window]
padding.x = 16
padding.y = 14
decorations = "None"
opacity = 0.98

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]